---
- hosts: all
  become: true
  gather_facts: true
  collections: community.mysql.mysql_info
  tasks:
    - name: install prerequisites
      apt:
        pkg:
          - wget
          - net-tools
          
    - name: Install zabbix
      apt:
        deb: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb
        
    - name: Apt update
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
        
    - name: Install mysql, php and apache modules
      apt:
        pkg:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-apache-conf
          - zabbix-agent
      
    - name: Install Mysql
      apt:
        pkg:
          - mysql-server
