---
- hosts: all
  become: true
  collections: 
    - community.mysql
  gather_facts: true
  tasks:
    - name: install prerequisites
      apt:
        pkg:
          - wget
          - net-tools
          
    - name: Install zabbix
      apt:
        deb: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb
        
    - name: Apt update
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
        
    - name: Install mysql, php and apache modules
      apt:
        pkg:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-apache-conf
          - zabbix-agent
      
    - name: Install Mysql
      apt:
        pkg:
          - mysql-server
          - python3-pip
          - libmysqlclient-dev
          - python3-dev
          - python3-mysqldb
          
    - name: Collect all
      community.mysql.mysql_info:
        login_user: root
      register: results
    - name: collect  
      debug:
        msg: "{{ results.stdout }}"
        
    - name: Collect info about databases and version using ~/.my.cnf as a credential file
      become: yes
      community.mysql.mysql_info:
        filter:
          - databases
          - version
          
    - name: Create a new database with name 'zabbix'
      community.mysql.mysql_db:
        name: zabbix
        state: present
